---

#Manage Files
#- hosts: all
#  become: true
#  tasks:

#  - name: install updates (Ubuntu)
#    tags: always
#    apt:
#      upgrade: dist
#      update_cache: yes
#    when: ansible_distribution  == "Ubuntu"

#  - name: install updates(centos)
#    dnf:
#      update_only: yes
#      upadte_cache: yes
#    when: ansible_distribution == "Centos"

- hosts: all
  become: true
  roles:
    - base
  tasks:

  - name: create simone user
    tags: always
    user:
      name: simone
      groups: root

  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCgqgAcmCRvOx7mz8fAR1Yd2QXg2NDj7fvmD+Ilm4czcLsOfuvnXRO5Yzfvg5gLeYNuRDOlj/Oa1V3xA5W8X078flsBYT4fZUFbCL297kJoTM9vtCAan674bq7dEoBBoYmkxpER4bX2ttpAZ8kgNX+ECkqCaRYeCDTDXAUYWF5QkD45bU0iVEv7OzScWXTMmO9oY/dLSYGTJ6EeQJ8oe/MjZx86Ipos6ICPlsiYvCMrmpvHYwkwZqaTcSk3rV7BgGaFJV19fKXWqnO+QUHLSvADG7FhZLbl+qxcKFqWHOJZmqHjOyEUuwhXBCL4FPn5Ysp0veIOnvJvLHdwgff9al870tVbnKnkJPLpWMMgYxgxxo9KzSfxuWN7e/4aKXRBWSOYV2iJHyW8CYSMn4LpUwApOqzbFyJHxlC8ZkdpbZra7H9bvGG+DF/JU0PVipa+GbIIfGreUXwmlEZrAYH1+fIgKMxPI0r1mhKT6NLusXMywRWYd6BxR22FjH9vRadSeyOTAjGLesG8D6zdpVeBPitXEWkduFFND+IlvSKYqt2Wt4qJvo/eIIXdR5pDsHunx/b/y4/X7XZsmB6C/drSpdNNbsvHsfWUV5Q2zt6IJi7BjYTIsEuF1CYls5pT2GZ013q9SOYDZ3B1v6Aa/MSEebTFXSQ/5HdsM5eAGZsjlGBdQw== ubuntu@ubuntu"

  - name: add sudoers file for simone
    tags: always
    copy:
      src: sudoers_simone
      dest: /etc/sudoers.d/simone
      owner: root
      group: root
      mode: 0440

#- hosts: ansiblemn
#  become: true
#  tasks:

#  - name: install unzip
#    package:
#    name: unzip

#  - name: install terraform
#    unarchive:
#      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
#      dest: /usr/local/bin
#      remote_src: yes
#      mode: 0755
#      owner: root
#      group: root

- hosts: web_server
  become: true
  roles:
    - web_server
  tasks:

  - name: install apache and php packages for Ubuntu servers
    tags: apache,php,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest

# - name: change e-mail address fro admin
#   tags: apache,centos,httpd
#   lineinfile:
#    path: /etc/httpd/conf/httpd.conf
#     regexp: "ServerAdmin"
#     line: ServerAdmin somebody@somewhere.net
#   when: ansible_distribution == "CentOS"
#   register: httpd

# - name: restart httpd(CentOS)
#   tags: apache,centos,httpd
#   service:
#     name: httpd
#     state: restarted
#   when: httpd.changed

  -  name: copy default html file for site
     tags: apache,apache2,ubuntu
     copy:
        src: default_target.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644  #set permissions

- hosts: db_server
  become: true
  roles:
    - db_server
  tasks:

  - name: install mariadb package(Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

#Managing Services
# - name: start httpd (Centos)
#   tags: apache,centos,httpd
#   service:
#     name: httpd
#     state: started
#     enabled: yes     #- still disable so we need to enable
#     when: ansible_distriution == "Centos"
