---

#- hosts: all
#  become: true
#  tasks:

#  - name: install updates (Ubuntu)
#    tags: always
#    apt:
#      upgrade: dist
#      update_cache: yes
#    when: ansible_distribution  == "Ubuntu"

#  - name: install updates(centos)
#    dnf:
#      update_only: yes
#      upadte_cache: yes
#    when: ansible_distribution == "Centos"

- hosts: web_server
  become: true
  tasks:

  - name: install apache and php packages for Ubuntu servers
    tags: apache,php,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest

- hosts: db_server
  become: true
  tasks:

  - name: install mariadb package(Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"
